# Generated by Django 4.1.3 on 2022-12-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floorplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('fpId', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(max_length=500)),
                ('image2', models.CharField(max_length=500)),
                ('type1', models.CharField(max_length=500)),
                ('type2', models.CharField(max_length=500)),
                ('x_coordinate', models.CharField(max_length=500)),
                ('y_coordinate', models.CharField(max_length=500)),
            ],
        ),
    ]
