# Generated by Django 4.1.3 on 2022-12-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_floorplan_join'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Floorplan',
        ),
    ]
