# Generated by Django 4.1.3 on 2022-12-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_floorplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floorplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('fpId', models.CharField(max_length=500)),
                ('joins', models.ManyToManyField(to='api.join')),
            ],
        ),
    ]
