# Base image
FROM node:14-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the desired port (e.g., 3000)
EXPOSE 3000

# Define the command to start the application
CMD ["npm", "start"]
